Loja/Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Loja.Models;
using PagedList;
using Core;

namespace Loja.Controllers
{
    public class FornecedorController : Controller
    {
            private ApplicationDbContext db = new ApplicationDbContext();

            public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NomeParam = String.IsNullOrEmpty(sortOrder) ? "RazaoSocial" : "";
                ViewBag.DateParm = sortOrder == "Date" ? "Date_desc" : "Date";


                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                var fornecedores = from s in db.Fornecedors
                                   select s;

                if (!String.IsNullOrEmpty(searchString))
                {
                    fornecedores = fornecedores.Where(s => s.RazaoSocial.ToUpper().Contains(searchString.ToUpper())
                                           || s.RazaoSocial.ToUpper().Contains(searchString.ToUpper()));
                }
                switch (sortOrder)
                {
                    case "RazaoSocial":
                        fornecedores = fornecedores.OrderByDescending(s => s.RazaoSocial);
                        break;
                    case "Data":
                        fornecedores = fornecedores.OrderBy(s => s.DataCadastro);
                        break;
                    case "Data_desc":
                        fornecedores = fornecedores.OrderByDescending(s => s.DataCadastro);
                        break;
                    default:
                        fornecedores = fornecedores.OrderBy(s => s.CNPJ);
                        break;
                }


                int pageSize = 6;
                int pageNumber = (page ?? 1);
                return View(fornecedores.ToPagedList(pageNumber, pageSize));
            }




            // GET: Fornecedor/Details/5
            public ActionResult Details(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Fornecedor fornecedor = db.Fornecedors.Find(id);
                if (fornecedor == null)
                {
                    return HttpNotFound();
                }
                return View(fornecedor);
            }

            // GET: Fornecedor/Create
            public ActionResult Create()
            {
                return View();
            }

            // POST: Fornecedor/Create
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Create([Bind(Include = "Id,Nome,tipoPessoa,CNPJ,RazaoSocial,Ativo,DataCadastro")] Fornecedor fornecedor)
            {
                if (ModelState.IsValid)
                {
                    fornecedor.Ativo = true;
                    fornecedor.DataCadastro = DateTime.Now;
                    db.Fornecedors.Add(fornecedor);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(fornecedor);
            }

            // GET: Fornecedor/Edit/5
            public ActionResult Edit(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Fornecedor fornecedor = db.Fornecedors.Find(id);
                if (fornecedor == null)
                {
                    return HttpNotFound();
                }
                return View(fornecedor);
            }

            // POST: Fornecedor/Edit/5
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit([Bind(Include = "Id,Nome,tipoPessoa,CNPJ,RazaoSocial,Ativo,DataCadastro")] Fornecedor fornecedor)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(fornecedor).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(fornecedor);
            }

            // GET: Fornecedor/Delete/5
            public ActionResult Delete(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Fornecedor fornecedor = db.Fornecedors.Find(id);
                if (fornecedor == null)
                {
                    return HttpNotFound();
                }
                return View(fornecedor);
            }

            // POST: Fornecedor/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public ActionResult DeleteConfirmed(int id)
            {
                Fornecedor fornecedor = db.Fornecedors.Find(id);
                db.Fornecedors.Remove(fornecedor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }

        // GET: MotivoForn/Create
        public ActionResult Inativar()
        {
            ViewBag.fornecedo = new SelectList(db.Fornecedors, "Id", "RazaoSocial");
            return View();
        }

        // POST: MotivoForn/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Inativar([Bind(Include = "id,DataMotivo,fornecedo,Usuario,MotivoAtivacao,MotivoInativacao")] MotivoForn motivoForn)
        {
            if (ModelState.IsValid)
            {
                db.MotivoForns.Add(motivoForn);
                Fornecedor fornecedor = db.Fornecedors.Find(motivoForn.id);
                motivoForn.Usuario = User.Identity.Name;
                motivoForn.DataMotivo = DateTime.Now;
                fornecedor.Ativo = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.fornecedo = new SelectList(db.Fornecedors, "Id", "RazaoSocial", motivoForn.fornecedo);
            return View(motivoForn);
        }

        // GET: MotivoForn/Create
        public ActionResult Ativar()
        {
            ViewBag.fornecedo = new SelectList(db.Fornecedors, "Id", "RazaoSocial");
            return View();
        }

        // POST: MotivoForn/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ativar([Bind(Include = "id,DataMotivo,fornecedo,Usuario,MotivoAtivacao,MotivoInativacao")] MotivoForn motivoForn)
        {
            if (ModelState.IsValid)
            {
                db.MotivoForns.Add(motivoForn);
                Fornecedor fornecedor = db.Fornecedors.Find(motivoForn.id);
                motivoForn.Usuario = User.Identity.Name;
                motivoForn.DataMotivo = DateTime.Now;
                fornecedor.Ativo = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.fornecedo = new SelectList(db.Fornecedors, "Id", "RazaoSocial", motivoForn.fornecedo);
            return View(motivoForn);
        }
    }
    }

Loja/Views/FornecedorViewModel/Index.cshtml
@using PagedList.Mvc; 
@model PagedList.IPagedList<Loja.Models.Fornecedor>
@{
    ViewBag.Title = "Listagem Fornecedores";
}
<div class="container">
    <h2>Listagem Fornecedores</h2>
    <p>
        @Html.ActionLink("Adicionar Novo", "Create","Fornecedor",null, new { @class = "btn btn-primary"})
    </p>
    @using (Html.BeginForm("Index", "Fornecedor", FormMethod.Get))
    {
        <p>
            Procura por RazaoSocial : @Html.TextBox("SearchString")
            <input type="submit" value="Busca" />
        </p>
    }
    <table class="table">
        <tr>
            <th>@Html.ActionLink("RazaoSocial", "Index", "Fornecedor", new { sortOrder = ViewBag.NomeParam })</th>
            <th>Tipo Pessoa</th>
            <th>CNPJ</th>
            <th>Ativo</th>
            <th>@Html.ActionLink("Data Cadastro", "Index", "Fornecedor", new { sortOrder = ViewBag.DateParam })</th>
            <th></th>
            <th></th>
          

            @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.RazaoSocial)</td>
                <td>@Html.DisplayFor(modelItem => item.tipoPessoa)</td>
                <td>@Html.DisplayFor(modelItem => item.CNPJ)</td>
                <td>@Html.DisplayFor(modelItem => item.Ativo)</td>
                <td>@Html.DisplayFor(modelItem => item.DataCadastro)</td>
                <td>@Html.ActionLink("Editar", "Edit", "Fornecedor",  new { id = item.Id }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Detalhes", "Details", "Fornecedor", new { id = item.Id }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Deletar", "Delete", "Fornecedor",  new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>

            </tr>
            }

        </table>
    </div>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount)
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))