Loja/Controllers/CheckoutController.cs
using Core;
using Dominio;
using Loja.Models;
using Loja.Models.Carrinho;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Loja.Controllers
{
    public class CheckoutController : Controller
    {
        // GET: Checkout
        ApplicationDbContext storeDB = new ApplicationDbContext();
        static int endere;
        static decimal valorView;
        static bool cupons;
        static int cupo;
        // GET: Checkout
        public ActionResult Index()
        {
            var cart = CarrinhoDeCompras.GetCart(this.HttpContext);
            // Set up our ViewModel
            var viewModel = new CarrinhodeComprasViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),

            };
            // Retorna a view

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult ClienteFormadePagamento3(string pagamento, int? id, int? cartao, decimal? valor)
        {
            ViewBag.Cupom = "Cupom Ínvalido";
            string Codigo = (Request.Form["cup"]);
            Cupom cupom = storeDB.Cupom.Where(x => x.Codigo == Codigo).FirstOrDefault();
            if (cupom != null)
            {
                if (cupom.Ativo == false || cupom.Codigo == null)
                {
                    return RedirectToAction("ListagemCartao");
                }
            }
            cupons = true;
            cupo = cupom.Id;
            valor = cupom.Valor;
            return orc(pagamento, id, cartao, valor, cupom.Codigo);
        }

        [HttpPost]
        public ActionResult ClienteFormadePagamento2(string pagamento, int? id, int? cartao, decimal? valor, string cupom)
        {
            decimal dec = 0;
            decimal.TryParse(Request.Form["dev"], out dec);
            valor = dec;
            return orc(pagamento, id, cartao, valor, cupom);
        }
        public static decimal valor;
        public ActionResult ClienteFormadePagamento(string pagamento, int? id, int? cartao, decimal? valor, bool? dife, string cupom)
        {
            return orc(pagamento, id, cartao, valor, cupom);
        }
        public ActionResult orc(string pagamento, int? id, int? cartao, decimal? valor, string cupom)
        {
            if (endere == 0)
            {
                //se o id recebido for nulo
                //manda cadastrar endereço
                //senão acha o endereço e salve-o
                if (id == null)
                {
                    endere = 0;
                    return RedirectToAction("EscolhaEndereco");
                }
                else
                {
                    EnderecoEntrega end = storeDB.EnderecoEntregas.Find(id);
                    endere = id.Value;
                    if (end == null)
                    {
                        return HttpNotFound();
                    }
                }
            }
            valor = (valor == null) ? 0 : valor;
            var cart = CarrinhoDeCompras.GetCart(this.HttpContext);
            foreach (var r in storeDB.Cartaos.ToList())
            {
                if (Request.Form[r.Id.ToString()] != null)
                {
                    cartao = int.Parse(Request.Form[r.Id.ToString()]);
                    break;
                }

            }
            var cards = new List<Pagamento>();
            decimal valord = (decimal)valor;
            //if (cupom == null)
            {

                Cartao card = null;
                if (cartao != null)
                    card = storeDB.Cartaos.Find(cartao);
                //var cards = new List<Pagamento>();//lista de cartoes
                //adiciona cartao na sessão
                //cria uma lista de obj cartoes na sessao
                if (Session["cards"] != null)
                    cards = (List<Pagamento>)Session["cards"];
                if (card != null)
                    cards.Add(new Pagamento() { Cartaoid = card.Id, Valor = valord });
                Session["cards"] = cards;

            }
            if (cupom != null)
            {
                //Cupom cup = storeDB.Cupom.Find(cupom);
                Cupom cup = storeDB.Cupom.Where(x => x.Codigo == cupom).FirstOrDefault();
                Session["cup_pro"] = cup;
                if (cup == null)
                {
                    return HttpNotFound();
                }
                cupons = true;
            }
            // Set up our ViewModel
            var viewModel = new CarrinhodeComprasViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),

            };
            decimal mountcard = 0;
            foreach (Pagamento pag in cards)
            {
                mountcard += pag.Valor;
                if (mountcard > cart.GetTotal())
                {
                    mountcard = 0;
                    mountcard += pag.Valor;
                }
            }
            if (Session["cup_pro"] != null)
                mountcard += ((Cupom)Session["cup_pro"]).Valor;
            // Retorna a view
            //viewModel.FormaPagamento = pagamento;
            valorView = viewModel.CartTotal - mountcard;
            viewModel.FormaPagamento = cartao.ToString();
            viewModel.EndId = endere;
            if (cart.GetTotal() == mountcard)
            {
                valorView = 0;
                return View("ClienteFormadePagamento", viewModel);
            }
            else
            {
                return RedirectToAction("ListagemCartao");
            }
        }

        public ActionResult EscolhaEndereco()
        {
            return View(storeDB.EnderecoEntregas.ToList());
        }

        public ActionResult ListagemCartao()
        {
            var cart = CarrinhoDeCompras.GetCart(this.HttpContext);
            // Set up our ViewModel
            var viewModel = new CarrinhodeComprasViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),

            };
            ViewBag.Falta = valorView;
            ViewBag.Total = viewModel.CartTotal;
            return View(new Tuple<Pagamento, List<Cartao>>(new Pagamento(), storeDB.Cartaos.ToList()));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ClienteFormadePagamento(FormCollection values, int? id, int? cartao)
        {
            int dec = 0;
            int.TryParse(Request.Form["FormaPagamento"], out dec);
            cartao = dec;
            EnderecoEntrega end = storeDB.EnderecoEntregas.Find(endere);
            if (end == null)
            {
                return HttpNotFound();
            }

            ViewBag.Clientes = storeDB.Users;
            var order = new Pedido();
            TryUpdateModel(order);

            try
            {
                order.FormaPagamento = " ";
                order.Usuario = User.Identity.Name;
                order.DataPedido = DateTime.Now;
                order.Endereco = end.Id;
                order.Total = CarrinhoDeCompras.GetCart(this.HttpContext).GetTotal();
                //Salva o Pedido
                storeDB.Pedidoes.Add(order);
                storeDB.SaveChanges();
                var cart = CarrinhoDeCompras.GetCart(this.HttpContext);
                cart.CreateOrder(order, (List<Pagamento>)Session["cards"], (Cupom)Session["cup_pro"]);
                Session["cards"] = null;
                Session["cup_pro"] = null;
                PedidoStatus stats = new PedidoStatus();
                stats.DataStatus = DateTime.Now;
                stats.PedidoId = order.PedidoId;
                stats.StatusId = 1;
                storeDB.PedidoStatus.Add(stats);
                storeDB.SaveChanges();
                if (cupons == true)
                {
                    Cupom cup = storeDB.Cupom.Find(cupo);
                    cup.Ativo = false;
                }
                storeDB.SaveChanges();

                return RedirectToAction("Complete", new { id = order.PedidoId });
            }
            catch
            {
                //Invalido - Devolve tela com erros
                return View(order);
            }

        }
        public ActionResult Complete(int id)
        {
            // Valida o pedido para o Usuário
            bool isValid = storeDB.Pedidoes.Any(
                o => o.PedidoId == id);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }


        public ActionResult EnderecoEntrega()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EnderecoEntrega([Bind(Include = "CEP,Estado,Cidade,Bairro,Logradouro,Numero,Observacao,DataCadastro")] EnderecoEntrega localEntrega)
        {
            if (ModelState.IsValid)
            {
                localEntrega.DataCadastro = DateTime.Now;
                localEntrega.Usuario = User.Identity.Name;
                storeDB.EnderecoEntregas.Add(localEntrega);
                storeDB.SaveChanges();
                return RedirectToAction("ClienteFormadePagamento");
            }

            return View(localEntrega);
        }

    }
}

Loja/Controllers/EnderecoEntregaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Loja.Models;
using Core;

namespace Loja.Controllers
{
    public class EnderecoEntregaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: EnderecoEntrega
        public ActionResult Index()
        {
            return View(db.EnderecoEntregas.ToList());
        }

        // GET: EnderecoEntrega/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnderecoEntrega enderecoEntrega = db.EnderecoEntregas.Find(id);
            if (enderecoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(enderecoEntrega);
        }

        // GET: EnderecoEntrega/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EnderecoEntrega/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CEP,Estado,Cidade,Bairro,Logradouro,Numero,Observacao,DataCadastro,Ativo")] EnderecoEntrega enderecoEntrega)
        {
            if (ModelState.IsValid)
            {
                enderecoEntrega.Usuario = User.Identity.Name;
                enderecoEntrega.DataCadastro = DateTime.Now;
                db.EnderecoEntregas.Add(enderecoEntrega);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(enderecoEntrega);
        }

        // GET: EnderecoEntrega/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnderecoEntrega enderecoEntrega = db.EnderecoEntregas.Find(id);
            if (enderecoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(enderecoEntrega);
        }

        // POST: EnderecoEntrega/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CEP,Estado,Cidade,Bairro,Logradouro,Numero,Observacao,DataCadastro,Ativo")] EnderecoEntrega enderecoEntrega)
        {
            if (ModelState.IsValid)
            {
                enderecoEntrega.Usuario = User.Identity.Name;
                enderecoEntrega.DataCadastro = DateTime.Now;
                db.Entry(enderecoEntrega).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(enderecoEntrega);
        }

        // GET: EnderecoEntrega/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnderecoEntrega enderecoEntrega = db.EnderecoEntregas.Find(id);
            if (enderecoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(enderecoEntrega);
        }

        // POST: EnderecoEntrega/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EnderecoEntrega enderecoEntrega = db.EnderecoEntregas.Find(id);
            db.EnderecoEntregas.Remove(enderecoEntrega);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Loja/Views/Checkout/ClienteFormadePagamento.cshtml
@model Loja.Models.Carrinho.CarrinhodeComprasViewModel

<div class="container">
    <div class="create">
        <br />
        <h2>Confirmação</h2>


        @using (Html.BeginForm("ClienteFormadePagamento", "Checkout", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <h3><em>Confirmação do pedido</em></h3>
            <div>
                @for (int i = 0; i < Model.CartItems.Count; i++)
                {
                <p>@Html.ValidationMessageFor(model => model.CartItems[i].Quantidade)</p>
                }
            </div>
            <div id="update-message"></div>
            <table>
                <tr>
                    <th>Nome do Produto</th>
                    <th>Preço (cada)</th>
                    <th>Quantidade</th>
                    <th></th>
                    <th></th>
                    <th>Em estoque</th>
                </tr>

                @foreach (var item in Model.CartItems)
                {
                    <tr id="row-@item.RecordId">
                        <td>@Html.ActionLink(item.Produto.Titulo, "Details", "Produto", new { id = item.ProdutoId }, null)</td>
                        <td>@item.Produto.ValorFinal</td>
                        <td align="right">
                            @*id="item-count-@item.RecordId">
                              @item.Count*@
                            <div class="col-md-2">
                                @item.Quantidade
                            </div>
                        </td>
                        <td></td>
                        <td></td>

                    </tr>
                }
                <tr>
                    <td>
                        Total (R$)
                    </td>
                    <td></td>

                    <td id="cart-total">
                        @Model.CartTotal
                    </td>
                </tr>
            </table>
            <input type="submit" value="Complete" class="btn btn-success" />

        }
        <div>
            @Html.ActionLink("Voltar", "Index", "CarrinhodeCompras")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>
</div>

Loja/Views/Checkout/Complete.cshtml
@{
    ViewBag.Title = "Checkout Complete";
}
<div class="container">
    <div class="create">
        <br />
        <h2>Pedido Completo</h2>
        <p>O pedido de codigo @Model foi adicionado  com sucesso</p>
        <p>
            @Html.ActionLink("Voltar ao Inicio", "Index", "Home",null, new { @class = "btn btn-success" })
        </p>
    </div>
</div>

Loja/Views/Checkout/EnderecoEntrega.cshtml
@model Loja.Models.EnderecoEntrega


<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>EnderecoEntrega</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Logradouro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Logradouro, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Logradouro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </div>

Loja/Views/Checkout/EscolhaEndereco.cshtml
@model IEnumerable<Loja.Models.EnderecoEntrega>

<div class="container">
    <br />
    <h3>Endereço Cadastrados</h3>
    <br />
    <p>
        @Html.ActionLink("Adicionar Novo", "EnderecoEntrega")
    </p>
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.CEP)</th>
            <th>@Html.DisplayNameFor(model => model.Estado)</th>
            <th>@Html.DisplayNameFor(model => model.Cidade)</th>
            <th>@Html.DisplayNameFor(model => model.Bairro)</th>
            <th>@Html.DisplayNameFor(model => model.Logradouro)</th>
            <th>@Html.DisplayNameFor(model => model.Numero)</th>
            <th>@Html.DisplayNameFor(model => model.Observacao)</th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (User.Identity.Name == item.Usuario)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.CEP)</td>
                    <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                    <td>@Html.DisplayFor(modelItem => item.Cidade)</td>
                    <td>@Html.DisplayFor(modelItem => item.Bairro)</td>
                    <td>@Html.DisplayFor(modelItem => item.Logradouro)</td>
                    <td>@Html.DisplayFor(modelItem => item.Numero)</td>
                    <td>@Html.DisplayFor(modelItem => item.Observacao)</td>
                    <td>@Html.ActionLink("Editar", "Edit","EnderecoEntrega", new { id = item.Id }, new { @class = "btn btn-primary" })</td>
                    <td>@Html.ActionLink("Deletar", "Delete", "EnderecoEntrega", new { id = item.Id }, new { @class = "btn btn-danger" })</td>
                    <td>@Html.ActionLink("Escolher", "ClienteFormadePagamento", null, new { id = item.Id }, new { @class = "btn btn-success" })</td>
                </tr>
            }
        }

    </table>
</div>

Loja/Views/Checkout/ListagemCartao.cshtml
@model  Tuple<Loja.Models.Carrinho.Pagamento, List<Loja.Models.Cartao>>

@{
    ViewBag.Title = "Listagem Cartões";
}

<div class="container">
    <h2>Listagem Cartões</h2>

    
    @using (Html.BeginForm("ClienteFormadePagamento2", "Checkout", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

    <p>
        @Html.ActionLink("Adicionar Novo", "Create");
    </p>

    <h5>Ao escolher somente um cartão digite no campo abaixo o valor total e ecolha o cartão</h5>
            <h5>
                Ao escolher dois cartões digite no campo abaixo o valor que você quer pagar
                e escolha o cartão e aperte escolher, após isso digite novamente o valor e escolha o outro cartão.
            </h5>

     <p>Valor Total da Compra: @ViewBag.Total</p>
    <p>Valor a pagar no cartão:  @Html.TextBox("dev")</p>
    <p>Valor que valta a pagar @ViewBag.Falta</p>
    <table class="table">
        <tr>
            <th>NomeCartao</th>
            <th>NumeroCartao)</th>
            <th>DataExpira</th>
            <th>CVV</th>
            <th></th>
        </tr>
        
        @foreach (var item in Model.Item2)
        {
            if (User.Identity.Name == item.Usuario)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.NomeCartao)</td>
                    <td>@Html.DisplayFor(modelItem => item.NumeroCartao)</td>
                    <td>@Html.DisplayFor(modelItem => item.DataExpira)</td>
                    <td>@Html.DisplayFor(modelItem => item.CVV)</td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", null, new { id = item.Id }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Deletar", "Delete", null, new { id = item.Id }, new { @class = "btn btn-danger" })
                        <input type="hidden" name="@item.Id" value="@item.Id"  />
                        <input type="submit" name="go" value="Escolher" class="btn btn-success" />
                        
                    </td>
                    
                </tr>
            }
        }
       
    </table>
    }
    <script>
        function go(atri) 
        {
            /*
            $.ajax({
                url: "Url.Action("ClienteFormadePagamento", "Checkout")",
                data: { 'cartao': atri, 'valor': document.getElementById('Item1_Valor').value },
                type: 'GET',
                context: document.body,
                timeout:300000,
                success: function (result) {
                    //do the necessary updations
                },
                error: function (result) {
                   alert('as')
                }
            });
            */
            document.href = "/Checkout/ClienteFormadePagamento?cartao=atri&valor="+document.getElementById('Item1_Valor').value;
        }


    </script>
@using (Html.BeginForm("ClienteFormadePagamento3", "Checkout", FormMethod.Post))
{
    <p>Insira Cupom:  @Html.TextBox("cup")</p>
    <input type="submit" name="go" value="Escolher" class="btn btn-success" />
}
</div>