Loja/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Loja.Models;
using Loja.Models.Carrinho;
using Core;

namespace Loja.Controllers
{
    public class PedidoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Pedido
        public ActionResult Index()
        {
            return View(db.Pedidoes.ToList());
        }

        // GET: Pedido/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ClasseModeladora cm = new ClasseModeladora() { DB = db };
            cm.Preencher(id);
            Pedido pedido = db.Pedidoes.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(cm);
        }

        // GET: Pedido/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pedido/Create
        // GET: Pedido/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidoes.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pedido pedido = db.Pedidoes.Find(id);
            db.Pedidoes.Remove(pedido);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Loja/Controllers/PedidoStatusController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Loja.Models.Carrinho;
using Core;
using PagedList;
using Dominio;
using Loja.Models;

namespace Loja.Controllers
{
    public class PedidoStatusController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PedidoStatus

        //-----------------------------
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NomeParam = String.IsNullOrEmpty(sortOrder) ? "PedidoId" : "";
            ViewBag.NomeStatus = String.IsNullOrEmpty(sortOrder) ? "Status" : "";
            ViewBag.DateParm = sortOrder == "Date" ? "Date_desc" : "Date";
            
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var pedidoStatus = from s in db.PedidoStatus
                               select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                pedidoStatus = pedidoStatus.Where(s => s.PedidoId.ToString().ToUpper().Contains(searchString.ToUpper())
                                       || s.PedidoId.ToString().ToUpper().Contains(searchString.ToUpper())
                                       || s.StatusId.ToString().ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "PedidoId":
                    pedidoStatus = pedidoStatus.OrderByDescending(s => s.PedidoId);
                    break;
                case "Status":
                    pedidoStatus = pedidoStatus.OrderByDescending(s => s.StatusId);
                    break;
                case "Data":
                    pedidoStatus = pedidoStatus.OrderBy(s => s.DataStatus);
                    break;
                case "Data_desc":
                    pedidoStatus = pedidoStatus.OrderByDescending(s => s.DataStatus);
                    break;
                default:
                    pedidoStatus = pedidoStatus.OrderBy(s => s.PedidoId);
                    break;
            }


            int pageSize = 12;
            int pageNumber = (page ?? 1);
            return View(pedidoStatus.ToPagedList(pageNumber, pageSize));
        }
        //-----------------------------


        // GET: PedidoStatus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoStatus pedidoStatus = db.PedidoStatus.Find(id);
            if (pedidoStatus == null)
            {
                return HttpNotFound();
            }
            return View(pedidoStatus);
        }

        // GET: PedidoStatus/Create
        public ActionResult Create()
        {
            ViewBag.PedidoId = new SelectList(db.Pedidoes, "PedidoId", "PedidoId");
            ViewBag.StatusId = new SelectList(db.Status, "id", "NomeStatus");
            return View();
        }

        // POST: PedidoStatus/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,PedidoId,StatusId,Usuario,DataStatus")] PedidoStatus pedidoStatus)
        {
            if (ModelState.IsValid)
            {
                pedidoStatus.Usuario = User.Identity.Name;
                pedidoStatus.DataStatus = DateTime.Now;
                db.PedidoStatus.Add(pedidoStatus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PedidoId = new SelectList(db.Pedidoes, "PedidoId", "Usuario", pedidoStatus.PedidoId);
            ViewBag.StatusId = new SelectList(db.Status, "id", "NomeStatus", pedidoStatus.StatusId);
            return View(pedidoStatus);
        }

        // GET: PedidoStatus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoStatus pedidoStatus = db.PedidoStatus.Find(id);
            if (pedidoStatus == null)
            {
                return HttpNotFound();
            }
            ViewBag.PedidoId = new SelectList(db.Pedidoes, "PedidoId", "Usuario", pedidoStatus.PedidoId);
            ViewBag.StatusId = new SelectList(db.Status, "id", "NomeStatus", pedidoStatus.StatusId);
            return View(pedidoStatus);
        }

        // POST: PedidoStatus/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,PedidoId,StatusId,Usuario,DataStatus")] PedidoStatus pedidoStatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedidoStatus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PedidoId = new SelectList(db.Pedidoes, "PedidoId", "Usuario", pedidoStatus.PedidoId);
            ViewBag.StatusId = new SelectList(db.Status, "id", "NomeStatus", pedidoStatus.StatusId);
            return View(pedidoStatus);
        }

        // GET: PedidoStatus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoStatus pedidoStatus = db.PedidoStatus.Find(id);
            if (pedidoStatus == null)
            {
                return HttpNotFound();
            }
            return View(pedidoStatus);
        }

        // POST: PedidoStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PedidoStatus pedidoStatus = db.PedidoStatus.Find(id);
            db.PedidoStatus.Remove(pedidoStatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult TrocaPedido(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidoes.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.PedidoId = pedido.PedidoId;
            return View();
        }

        // POST: PedidoStatus/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TrocaPedido(PedidoStatus pedidoStatus,int? id)
        {
            Pedido pedido = db.Pedidoes.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                pedidoStatus.PedidoId = pedido.PedidoId;
                pedidoStatus.Usuario = User.Identity.Name;
                pedidoStatus.DataStatus = DateTime.Now;
                pedidoStatus.StatusId = 7;
                db.PedidoStatus.Add(pedidoStatus);
                db.SaveChanges();
                return RedirectToAction("Index","Pedido");
            }

            ViewBag.PedidoId = new SelectList(db.Pedidoes, "PedidoId", "Usuario", pedidoStatus.PedidoId);
            ViewBag.StatusId = new SelectList(db.Status, "id", "NomeStatus", pedidoStatus.StatusId);
            return View(pedidoStatus);
        }

        public ActionResult Negar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoStatus pedido = db.PedidoStatus.Where(x => x.PedidoId == id).FirstOrDefault();
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.PedidoId = pedido.PedidoId;
            return Negar(pedido, pedido.PedidoId);
        }

        // POST: PedidoStatus/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Negar(PedidoStatus pedidoStatus, int? id)
        {
            PedidoStatus pedido = db.PedidoStatus.Where(x => x.PedidoId == id).FirstOrDefault();
            if (pedido == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                //cria pedidoStatus
                pedidoStatus.id = pedido.id;
                pedidoStatus.Usuario = User.Identity.Name;
                pedidoStatus.DataStatus = DateTime.Now;
                pedidoStatus.StatusId = 8;
                db.PedidoStatus.Add(pedidoStatus);
                db.SaveChanges();
                return RedirectToAction("Index", "Pedido");
            }
            return View(pedidoStatus);
        }

        public ActionResult Autorizar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoStatus pedido = db.PedidoStatus.Where(x => x.PedidoId == id).FirstOrDefault();
            if (pedido == null)
            {
                return HttpNotFound();
            }
            DetalhesPedido dpedido = db.DetalhesPedidoes.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            //ViewBag.produto = dpedido.ProdutoId;
            ViewBag.PedidoId = pedido.PedidoId;
            return Autorizar(pedido,pedido.PedidoId);
        }

        // POST: PedidoStatus/Create
        [HttpPost]

Loja/Views/Pedido/Details.cshtml
@model Loja.Models.Carrinho.ClasseModeladora

<div class="create">
    <br />
    <h1> &nbsp &nbsp Detalhes do Pedido</h1>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")


    <div class="container">
        <div class="">
            <hr />
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="h4">Pedido ID: @Html.DisplayFor(model => model.Pedido.PedidoId)</div>
                </div>

            </div>
            <div class="row">
                @{if(!String.IsNullOrEmpty(Model.EnderecoEntrega.Estado))
                  {
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="h4">Estado: @Html.DisplayFor(model => model.EnderecoEntrega.Estado)</div>
                        </div>
                  }
                }
            </div>
            <div class="row">
                @{ if (!String.IsNullOrEmpty(Model.EnderecoEntrega.Cidade)){
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="h4">Cidade: @Html.DisplayFor(model => model.EnderecoEntrega.Cidade)</div>
                        </div>
                   }
                }
                @{ if (!String.IsNullOrEmpty(Model.EnderecoEntrega.Logradouro))
                   {
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="h4">Endereço: @Html.DisplayFor(model => model.EnderecoEntrega.Logradouro)</div>
                        </div>
                   }
                }
            </div>
            <div class="row">
                @{ if (!String.IsNullOrEmpty(Model.EnderecoEntrega.Bairro))
                   {
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="h4">Bairro: @Html.DisplayFor(model => model.EnderecoEntrega.Bairro)</div>
                        </div>
                   }
                }

            </div>
            <div class="row">
                @{ if (!String.IsNullOrEmpty(Model.EnderecoEntrega.Numero))
                   {
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="h4">Número: @Html.DisplayFor(model => model.EnderecoEntrega.Numero)</div>
                        </div>
                   }
                }

            </div>
        </div>
        <br />
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">Dados dos produtos</div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>Nome do Produto</th>
                        <th>Preço Unit</th>
                        <th>Quantidade</th>
                        <th>Preço Total</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.Produto)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => item.Id)</td>
                            <td>@Html.DisplayFor(model => item.Titulo)</td>
                            <td>@Html.DisplayFor(model => model.DetalhesPedidos.Where(x => x.ProdutoId == item.Id).FirstOrDefault().PrecoUnitario)</td>
                            <td>@Html.DisplayFor(model => model.DetalhesPedidos.Where(x => x.ProdutoId == item.Id).FirstOrDefault().Quantidade)</td>
                            <td>@(Model.DetalhesPedidos.Where(x => x.ProdutoId == item.Id).FirstOrDefault().Quantidade * Model.DetalhesPedidos.Where(x => x.ProdutoId == item.Id).FirstOrDefault().PrecoUnitario)</td>
                        </tr>
                    }
                </tbody>
                <tfoot class="bottom-right">
                    <tr>
                        <td class="" colspan="5">
                           
                            <div class="text-left h5">
                                @*Html.DisplayFor(model => model.Pedido.FormaPagamento)*@ 

                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>id</th>
                                            <th>Nome no Cartao</th>
                                            <th>Numero Cartao</th>
                                            <th>Data Expira</th>
                                            <th>CVV</th>
                                        </tr>
                                    </thead>
                                    @foreach (var item in Model.cartao)
                                    {
                                        if (Model.Pedido.Usuario == item.Usuario) {
                                        <tr>
                                            <td>@Html.DisplayFor(model => item.Id)</td>
                                            <td>@Html.DisplayFor(model => item.NomeCartao)</td>
                                            <td>@Html.DisplayFor(model => item.NumeroCartao)</td>
                                            <td>@Html.DisplayFor(model => item.DataExpira)</td>
                                            <td>@Html.DisplayFor(model => item.CVV)</td>
                                            
                                        </tr>
                                        }
                                    }
                                </table>
                            </div>
                            <div class="text-right h5">
                                <strong>Total: @Html.DisplayFor(model => model.Pedido.Total) R$ </strong>
                            </div>
                        </td>
                    </tr>
                </tfoot>

            </table>
        </div>
    </div>
</div>
<div class="container">
    <table class="table table-bordered">
        <thead>
            <tr>
                @*<th>PedidoId</th>*@
                <th>Status</th>
            </tr>
        </thead>
        @foreach (var item in Model.status)
        {
            if (Model.Pedido.PedidoId == item.pedi.PedidoId)
            {
                <tr>
                    @*<td>@Html.DisplayFor(model => item.pedi.PedidoId)</td>*@
                    <td>
                        @Html.DisplayFor(model => item.statu.NomeStatus)
                    <br />
                    @Html.DisplayFor(model => item.DataStatus)
                </td>
            </tr>
            }
        }
    </table>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Trocar Pedido", "TrocaPedido","PedidoStatus", new  { id  = Model.Pedido.PedidoId  }, new { @class = "btn btn-primary" })
</div>

Loja/Views/Pedido/Index.cshtml
@model IEnumerable<Loja.Models.Carrinho.Pedido>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="create">
        <br>
        <h2>Listagem de Pedidos</h2>

        <table class="table">
            <tr>
                <th>@Html.DisplayNameFor(model => model.PedidoId)</th>
                <th>@Html.DisplayNameFor(model => model.FormaPagamento)</th>
                <th>@Html.DisplayNameFor(model => model.DataPedido)</th>
                <th>@Html.DisplayNameFor(model => model.Usuario)</th>
                <th>@Html.DisplayNameFor(model => model.Total)</th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {

                <tr>
                    <th>@Html.DisplayFor(model => item.PedidoId)</th>
                    <td>@Html.DisplayFor(modelItem => item.FormaPagamento)</td>
                    <th>@Html.DisplayFor(model => item.DataPedido)</th>
                    <th>@Html.DisplayFor(model => item.Usuario)</th>
                    <th>R$ @Html.DisplayFor(model => item.Total)</th>

                    <td>@Html.ActionLink("Detalhes", "Details", null, new { id = item.PedidoId }, new { @class = "btn btn-default" })</td>
                </tr>

            }

        </table>
    </div>
</div>