Loja/Controllers/CarrinhodeComprasController.cs
using Core;
using Loja.Models;
using Loja.Models.Carrinho;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Loja.Controllers
{
    public class CarrinhoDeComprasController : Controller
    {
        ApplicationDbContext storeDB = new ApplicationDbContext();
        //
        // GET: /ShoppingCart/
        

        public ActionResult Index()
        {
            var cart = CarrinhoDeCompras.GetCart(this.HttpContext);
            // Set up our ViewModel
            var viewModel = new CarrinhodeComprasViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),
               
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5



        public ActionResult AddToCart(int id)
        {
            // Recupera o álbum do banco de dados
            var addProduto = storeDB.Produtoes
                .Single(produto => produto.Id == id);

            // Adiciona ao ItemVenda de compras
            var cart = CarrinhoDeCompras.GetCart(this.HttpContext);

            cart.AddToCart(addProduto);

            // Volta para a página da loja principal para mais compras
            return RedirectToAction("Index", "Home", null);
        }
        [HttpPost]
        public ActionResult UpdateCartCount(int id, int cartCount)
        {
            CarrinhodeComprasRemoverViewModel results = null;
            try
            {
                // Obtein o ItemVenda
                var cart = CarrinhoDeCompras.GetCart(this.HttpContext);

                // Pega o nome do álbum para exibir a confirmação
                string albumName = storeDB.ItemVendaes.Single(item => item.RecordId == id).Produto.Titulo;

                // Update a contagem do ItemVenda
                int itemCount = cart.UpdateCartCount(id, cartCount);

                //Prepara menssages
                string msg = "A quantidade de " + Server.HtmlEncode(albumName) +
                        " foi atualizada no ItemVenda";
                if (itemCount == 0) msg = Server.HtmlEncode(albumName) +
                        " foi removida do ItemVenda.";
                //
                // Mostra mensagem de confirmação 
                results = new CarrinhodeComprasRemoverViewModel
                {
                    Message = msg,
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
            }
            catch
            {
                results = new CarrinhodeComprasRemoverViewModel
                {
                    Message = "Erro ocorreu ou entrada inválida...",
                    CartTotal = -1,
                    CartCount = -1,
                    ItemCount = -1,
                    DeleteId = id
                };
            }
            return Json(results);
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove o item do ItemVenda
            var cart = CarrinhoDeCompras.GetCart(this.HttpContext);

            // Pega o nome do álbum para exibir a confirmação
            string nomeProduto = storeDB.ItemVendaes
                .Single(item => item.RecordId == id).Produto.Titulo;

            // Remove do ItemVenda
            int itemCount = cart.RemoveFromCart(id);

            // Mostra a confirmação da mensagem
            var results = new CarrinhodeComprasRemoverViewModel
            {
                Message = Server.HtmlEncode(nomeProduto) +
                    " Foi removido do ItemVenda.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = CarrinhoDeCompras.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
        [Authorize]
        public PartialViewResult Pagamento()
        {
            var cart = CarrinhoDeCompras.GetCart(this.HttpContext);


            return PartialView(cart);
        }

        // POST: Pedidoes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult Pagamento(ItemVenda cart)
        {
            if (ModelState.IsValid)
            {
                storeDB.Entry(cart).State = EntityState.Modified;
                storeDB.SaveChanges();
            }
            return PartialView(cart);
        }

    }

}

Loja/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Loja.Models;
using PagedList;
using Core;

namespace Loja.Controllers
{
    public class ProdutoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public PartialViewResult ProdutoP()
        {
            var produtos = from s in db.Produtoes.Where(x => x.Ativo)
                           select s;

            return PartialView(produtos.ToList());
        }
        public PartialViewResult QuantidadeEstoqueP(int? id)
        {
            EstoqueProdutos ep = new EstoqueProdutos();
            ApplicationDbContext ex = new ApplicationDbContext();
            if (ex.EstoqueProdutos.Where(x => x.Id == id).FirstOrDefault() != null)
                ViewBag.Quantidade = ex.EstoqueProdutos.Where(x => x.Id == id).Sum(x => x.Quantidade);
            else
                ViewBag.Quantidade = 0;

            return PartialView();
        }

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NomeParam = String.IsNullOrEmpty(sortOrder) ? "Titulo" : "";
            ViewBag.DateParm = sortOrder == "Date" ? "Date_desc" : "Date";

            if (searchString != null){
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var produtos = from s in db.Produtoes
                               select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                produtos = produtos.Where(s => s.Titulo.ToUpper().Contains(searchString.ToUpper())
                                       || s.Titulo.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Titulo":
                    produtos = produtos.OrderByDescending(s => s.Titulo);
                    break;
                case "Data":
                    produtos = produtos.OrderBy(s => s.DataCadastro);
                    break;
                case "Data_desc":
                    produtos = produtos.OrderByDescending(s => s.DataCadastro);
                    break;
                default:
                    produtos = produtos.OrderBy(s => s.Id);
                    break;
            }


            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(produtos.ToPagedList(pageNumber, pageSize));
        }

        // GET: Produto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            ViewBag.Fornecedor = new SelectList(db.Fornecedors, "Id", "RazaoSocial");
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Titulo,ImagemUrl,plataforma,idioma,legenda,DimensaodoProduto,genero,classificacaoIndicativa,Desenvolvedor,EspacoHd,ConteudoEmbalagem,Fornecedor,GarantiaFornecedor,Descricao1,Descricao2,ValorFinal,Ativo,DataCadastro")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                produto.Ativo = true;
                produto.DataCadastro = DateTime.Now;
                db.Produtoes.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Fornecedor = new SelectList(db.Fornecedors, "Id", "RazaoSocial", produto.Fornecedor);
            return View(produto);
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.Fornecedor = new SelectList(db.Fornecedors, "Id", "RazaoSocial", produto.Fornecedor);
            return View(produto);
        }

        // POST: Produto/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,ImagemUrl,plataforma,idioma,legenda,DimensaodoProduto,genero,classificacaoIndicativa,Desenvolvedor,EspacoHd,ConteudoEmbalagem,Fornecedor,GarantiaFornecedor,Descricao1,Descricao2,ValorFinal,Ativo,DataCadastro")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Fornecedor = new SelectList(db.Fornecedors, "Id", "RazaoSocial", produto.Fornecedor);
            return View(produto);
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtoes.Find(id);
            db.Produtoes.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //----------------------------------
        // GET: Motivo/Create
        public ActionResult Inativar()
        {
            ViewBag.ProdutoId = new SelectList(db.Produtoes, "Id", "Titulo");
            return View();
        }
        // POST: Motivo/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Inativar([Bind(Include = "id,DataMotivo,ProdutoId,Usuario,MotivoAtivacao,MotivoInativacao")] Motivo motivo)
        {
            if (ModelState.IsValid)
            {
                db.Motivoes.Add(motivo);
                Produto produto = db.Produtoes.Find(motivo.ProdutoId);
                motivo.DataMotivo = DateTime.Now;
                produto.Ativo = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProdutoId = new SelectList(db.Produtoes, "Id", "Titulo", motivo.ProdutoId);
            return View(motivo);
        }
        //----------------------------------
        // GET: Motivo/Create
        public ActionResult Ativar()
        {
            ViewBag.ProdutoId = new SelectList(db.Produtoes, "Id", "Titulo");
            return View();
        }

        // POST: Motivo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ativar([Bind(Include = "id,DataMotivo,ProdutoId,Usuario,MotivoAtivacao,MotivoInativacao")] Motivo motivo)
        {
            if (ModelState.IsValid)
            {
                db.Motivoes.Add(motivo);
                Produto produto = db.Produtoes.Find(motivo.ProdutoId);
                motivo.DataMotivo = DateTime.Now;
                produto.Ativo = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProdutoId = new SelectList(db.Produtoes, "Id", "Titulo", motivo.ProdutoId);
            return View(motivo);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Loja/Views/Produto/Ativar.cshtml
@model Loja.Models.Motivo


    <div class="container">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Motivo</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProdutoId, "ProdutoId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ProdutoId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProdutoId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MotivoAtivacao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MotivoAtivacao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MotivoAtivacao, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Voltar para Listagem", "Index",null,new { @class= "btn btn-default"})
    </div>
        </div>

Loja/Views/Produto/Delete.cshtml
@model Loja.Models.Produto


    
<div class="container">
        <h3>Você tem certeza que deseja excluir?</h3>

    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.forn.RazaoSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.forn.RazaoSocial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagemUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagemUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.plataforma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.plataforma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idioma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idioma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.legenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.legenda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DimensaodoProduto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DimensaodoProduto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.classificacaoIndicativa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.classificacaoIndicativa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desenvolvedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desenvolvedor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EspacoHd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EspacoHd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConteudoEmbalagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConteudoEmbalagem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GarantiaFornecedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GarantiaFornecedor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para Listagem", "Index",null,new { @class = "btn btn-default"})
        </div>
    }
</div>

Loja/Views/Produto/Details.cshtml
@model Loja.Models.Produto
@{
    ViewBag.Title = "Details";
}
<div class="container">
    <hr />
    <div class="Details">
        <div class="view">
            <div class="titulo">
                <h1> @Html.DisplayFor(model => model.Titulo)</h1>
            </div>
            <div class="Imagem">
                <img src="@Html.DisplayFor(model => model.ImagemUrl)" />
            </div>
            <div class="ViewD">
                <h3>
                    @Html.DisplayFor(model => model.Titulo) -
                    @Html.DisplayFor(model => model.plataforma) -
                    @Html.DisplayFor(model => model.genero) -
                    @Html.DisplayFor(model => model.idioma)
                </h3>
                <h1 style="color:red;">R$: @Html.DisplayFor(model => model.ValorFinal)</h1>
                <h1>@Html.DisplayFor(model => model.classificacaoIndicativa)</h1>
                <h3 class="button2">@Html.ActionLink("Adicionar", "AddToCart", "CarrinhoDeCompras", new { id = Model.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-shopping-cart" })</h3>
            </div>
        </div>
        <div class="Descricao">
            <h1 style="color:red;">Descrição</h1>
            <img src="@Html.DisplayFor(model => model.Descricao1)" />
            <br />
            @Html.DisplayFor(model => model.Descricao2)
        </div>
        <div class="Especificacao">
            <h4 style="color:red;">Especificação</h4>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.idioma)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.idioma)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.legenda)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.legenda)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.DimensaodoProduto)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.DimensaodoProduto)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.genero)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.genero)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Desenvolvedor)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Desenvolvedor)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.EspacoHd)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EspacoHd)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ConteudoEmbalagem)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ConteudoEmbalagem)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.GarantiaFornecedor)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.GarantiaFornecedor)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.classificacaoIndicativa)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.classificacaoIndicativa)
                </dd>
            </dl>
        </div>
        <div class="adm">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.ImagemUrl)
                <dt>
                <dd>
                    @Html.DisplayFor(model => model.ImagemUrl)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Ativo)
                <dt>
                <dd>
                    @Html.DisplayFor(model => model.Ativo)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.DataCadastro)
                <dt>
                <dd>
                    @Html.DisplayFor(model => model.DataCadastro)
                </dd>
            </dl>
        </div>
    </div>
</div>

<div class="navegacao"> 
    @Html.ActionLink("Editar", "Edit",null, new { id = Model.Id },new { @class="btn btn-primary"}) |
    @Html.ActionLink("Voltar para listagem", "Index",null,new { @class = "btn btn-default"})
</div>

Loja/Views/Produto/Inativar.cshtml
@model Loja.Models.Motivo

    <div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Motivo</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.ProdutoId, "ProdutoId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ProdutoId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProdutoId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MotivoInativacao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MotivoInativacao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MotivoInativacao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Loja/Views/Produto/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList <Loja.Models.Produto>

<div class="container">
    <br />
    <h3>Listagem de Produtos</h3>
    <p>
        @Html.ActionLink("Adicionar Novo", "Create",null,new { @class= "btn btn-primary" })
    </p>
    @using (Html.BeginForm("Index", "Produto", FormMethod.Get))
    {
        <p>
            Procura por Titulo : @Html.TextBox("SearchString")
            <input type="submit" value="Busca" />
        </p>
    }
    <table class="table">
        <tr>
            <th>Razão Social</th>
            <th>@Html.ActionLink("Titulo", "Index", new { sortOrder = ViewBag.NomeParam })</th>
            <th>Plataforma</th>
            <th>Gênero</th>
            <th>Valor Final</th>
            <th>Ativo</th>
            <th>@Html.ActionLink("Data Cadastro", "Index", new { sortOrder = ViewBag.DateParam })</th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.forn.RazaoSocial)</td>
                <td>@Html.DisplayFor(modelItem => item.Titulo)</td>
                <td>@Html.DisplayFor(modelItem => item.plataforma)</td>
                <td>@Html.DisplayFor(modelItem => item.genero)</td>
                <td>@Html.DisplayFor(modelItem => item.ValorFinal)</td>
                <td>@Html.DisplayFor(modelItem => item.Ativo)</td>
                <td>@Html.DisplayFor(modelItem => item.DataCadastro)</td>
                <td>
                    @Html.ActionLink("Editar", "Edit",null, new { id = item.Id },new { @class="btn btn-primary"})
                    @Html.ActionLink("Detalhes", "Details",null, new { id = item.Id },new { @class="btn btn-default"})
                    @Html.ActionLink("Deletar", "Delete",null, new { id = item.Id },new { @class = "btn btn-danger" })
                    @Html.ActionLink("Inativar", "Inativar",null, new { id = item.Id },new { @class = "btn btn-warning"})
                    @Html.ActionLink("Ativar", "Ativar",null, new { id = item.Id },new { @class = "btn btn-success"})
            </td>
        </tr>
        }

    </table>
    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, ordem = ViewBag.Ordenacao }))
</div>
      

Loja/Views/Produto/ProdutoP.cshtml
@model IEnumerable<Loja.Models.Produto>
@using (Html.BeginForm())
{
    foreach (var item in Model)
    {
        <div class="cartao">
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="#"><img class="card-img-top" src="@Url.Content(item.ImagemUrl)" alt="" width="200" height="130"></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            @Html.ActionLink( @item.Titulo, "Details", "Produto", new { id = item.Id }, null)
                        </h4>

                        <h5>Preço: R$ @item.ValorFinal  </h5>
                        <p class="card-text">@item.Descricao2</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        <p class="button2">@Html.ActionLink("Adicionar", "AddToCart", "CarrinhodeCompras", new { id = item.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-shopping-cart" })</p>
                    </div> 
                </div>
            </div>
        </div>
    }
}